FROM alpine:3.24

RUN apk add -U \
  automake \
  cmake \
  g++ \
  git \
  libtool \
  libxcursor-dev \
  libxi-dev mesa-dev \
  libxinerama-dev \
  libxrandr-dev \
  linux-headers \
  make \
  musl-dev \
  readline-dev \
  util-linux
