# We need gcc 8 for filesystem support
FROM alpine:3.12

RUN apk add -U libtool automake g++ git cmake make readline-dev musl-dev util-linux linux-headers libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev libgl1-mesa-dev
