add_subdirectory(api)
add_subdirectory(AircraftVehicleDemonstrator)
add_subdirectory(CompositeModels)
add_subdirectory(dcmotor)
add_subdirectory(parker)
add_subdirectory(simulation)
add_subdirectory(reference-fmus/2.0/cs)
add_subdirectory(reference-fmus/2.0/me)
add_subdirectory(reference-fmus/3.0/cs)
add_subdirectory(reference-fmus/3.0/me)
add_subdirectory(resources)
