# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - bug
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.
  Thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Closing this issue after a prolonged period of inactivity.
  If this issue is still present in the latest release, please feel free to create a new issue with up-to-date information.
# Optionally, specify configuration settings that are specific to just 'pulls':
pulls:
  daysUntilStale: 30
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs.
    Thank you for your contributions.
  closeComment: >
    Closing this pull request after a prolonged period of inactivity.
    If this is still relevant, please feel free to create a new pull request with up-to-date information.
