/* Additional record code for cs_source1 generated by the OpenModelica Compiler OMCompiler v1.12.0-dev.395+gdeeabde. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

