/* Simulation code for source1 generated by the OpenModelica Compiler OMCompiler v1.12.0-dev.395+gdeeabde. */
#if !defined(cs_source1__MODEL_H)
#define cs_source1__MODEL_H
#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <string.h>

#include "cs_source1_functions.h"


extern void cs_source1_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void cs_source1_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int cs_source1_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int cs_source1_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int cs_source1_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int cs_source1_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int cs_source1_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int cs_source1_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int cs_source1_checkForAsserts(DATA *data, threadData_t *threadData);
extern int cs_source1_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int cs_source1_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int cs_source1_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern int cs_source1_checkForDiscreteChanges(DATA *data, threadData_t *threadData);
extern const char* cs_source1_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* cs_source1_relationDescription(int i);
extern void cs_source1_function_initSample(DATA *data, threadData_t *threadData);
extern int cs_source1_initialAnalyticJacobianG(void* data, threadData_t *threadData);
extern int cs_source1_initialAnalyticJacobianA(void* data, threadData_t *threadData);
extern int cs_source1_initialAnalyticJacobianB(void* data, threadData_t *threadData);
extern int cs_source1_initialAnalyticJacobianC(void* data, threadData_t *threadData);
extern int cs_source1_initialAnalyticJacobianD(void* data, threadData_t *threadData);
extern int cs_source1_functionJacG_column(void* data, threadData_t *threadData);
extern int cs_source1_functionJacA_column(void* data, threadData_t *threadData);
extern int cs_source1_functionJacB_column(void* data, threadData_t *threadData);
extern int cs_source1_functionJacC_column(void* data, threadData_t *threadData);
extern int cs_source1_functionJacD_column(void* data, threadData_t *threadData);
extern const char* cs_source1_linear_model_frame(void);
extern const char* cs_source1_linear_model_datarecovery_frame(void);
extern int cs_source1_mayer(DATA* data, modelica_real** res, short *);
extern int cs_source1_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int cs_source1_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int cs_source1_setInputData(DATA *data, const modelica_boolean file);
extern int cs_source1_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void cs_source1_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void cs_source1_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int cs_source1_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void cs_source1_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void cs_source1_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int cs_source1_inputNames(DATA* data, char ** names);
extern int cs_source1_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int cs_source1_functionLocalKnownVars(DATA*, threadData_t*);
extern int cs_source1_symbolicInlineSystem(DATA*, threadData_t*);

#include "cs_source1_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#endif

