/* Additional record code for EventTest generated by the OpenModelica Compiler OpenModelica v1.25.0-dev-143-g6a0e852842 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "EventTest_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

