/* Simulation code for EventTest generated by the OpenModelica Compiler OpenModelica v1.25.0-dev-143-g6a0e852842 (64-bit). */
#if !defined(EventTest__MODEL_H)
#define EventTest__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "EventTest_functions.h"


extern void EventTest_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void EventTest_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int EventTest_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int EventTest_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int EventTest_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int EventTest_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int EventTest_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int EventTest_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int EventTest_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int EventTest_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int EventTest_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int EventTest_checkForAsserts(DATA *data, threadData_t *threadData);
extern int EventTest_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int EventTest_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int EventTest_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* EventTest_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* EventTest_relationDescription(int i);
extern void EventTest_function_initSample(DATA *data, threadData_t *threadData);
extern int EventTest_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int EventTest_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int EventTest_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int EventTest_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int EventTest_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int EventTest_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int EventTest_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int EventTest_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int EventTest_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int EventTest_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int EventTest_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int EventTest_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int EventTest_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int EventTest_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* EventTest_linear_model_frame(void);
extern const char* EventTest_linear_model_datarecovery_frame(void);
extern int EventTest_mayer(DATA* data, modelica_real** res, short *);
extern int EventTest_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int EventTest_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int EventTest_setInputData(DATA *data, const modelica_boolean file);
extern int EventTest_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void EventTest_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void EventTest_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int EventTest_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void EventTest_read_simulation_info(SIMULATION_INFO* simulationData);
extern void EventTest_read_input_fmu(MODEL_DATA* modelData);
extern void EventTest_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int EventTest_inputNames(DATA* data, char ** names);
extern int EventTest_dataReconciliationInputNames(DATA* data, char ** names);
extern int EventTest_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int EventTest_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int EventTest_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int EventTest_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "EventTest_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(EventTest__MODEL_H) */


